3-4

In [1]:
%pip install numpy
%pip install pandas


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd

3層ニューラルネットの実装

In [3]:
#設計
def sigmoid(x):
    return 1/(1+np.exp(-x))
def identity_function(x):
    return x
def init_network():
    network={}
    network['W1']=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1']=np.array([0.1,0.2,0.3])
    network['W2']=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2']=np.array([0.1,0.2])
    network['W3']=np.array([[0.1,0.3],[0.2,0.4]])
    network['b3']=np.array([0.1,0.2])

    return network
def forward(network,x):
    W1,W2,W3=network['W1'],network['W2'],network['W3']
    b1,b2,b3=network['b1'],network['b2'],network['b3']

    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    a3=np.dot(z2,W3)+b3
    y=identity_function(a3)

    return y

In [4]:
#実装
network=init_network()
x=np.array([1.0,0.5])
forward(network,x)

array([0.31682708, 0.69627909])

3-5 出力層の設計

In [5]:
a=np.array([0.3,2.9,4.0])
exp_a=np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [6]:
sum_exp_a=sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [7]:
exp_a/sum_exp_a

array([0.01821127, 0.24519181, 0.73659691])

In [8]:
#ソフトマックス関数の実装(仮)
def softmax(a):
    exp_a=np.exp(a)
    exp_a_sum=sum(exp_a)
    return exp_a/exp_a_sum

In [9]:
a=np.array([1010,1000,990])
softmax(a)
c=np.max(a)
np.exp(a-c)/np.sum(np.exp(a-c))

/var/folders/4s/g5jfy6yd0r5d8pcvsfwjr7v00000gn/T/ipykernel_96294/2100727282.py:3: RuntimeWarning: overflow encountered in exp
  exp_a=np.exp(a)
/var/folders/4s/g5jfy6yd0r5d8pcvsfwjr7v00000gn/T/ipykernel_96294/2100727282.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_a/exp_a_sum


array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [10]:
def softmax(a):
    c=np.max(a)
    exp_a=np.exp(a-c)
    exp_a_sum=np.sum(exp_a)
    y=exp_a/exp_a_sum

    return y

In [11]:
a=np.array([0.3,2.9,4.0])
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

In [12]:
np.sum(softmax(a))

np.float64(1.0)

3-6　手書き数字認識

In [2]:
import sys, os

# カレントディレクトリ確認
print("CWD:", os.getcwd())

# すでに追加されてるsys.pathを確認（デバッグ用）
print("Before sys.path:", sys.path)

# 一度重複を防ぐためにクリア（必要なら）
while './deep-learning-from-scratch-master' in sys.path:
    sys.path.remove('./deep-learning-from-scratch-master')

# 絶対パスを追加（ここが最重要！）
abs_path = '/Users/tanaamidaisuke/Documents/python_code/self_learinng/Deeplearning/deep-learning-from-scratch-master'
if abs_path not in sys.path:
    sys.path.insert(0, abs_path)

print("After sys.path:", sys.path)

# ここでimport（失敗したらエラー出る）
from dataset.mnist import load_mnist

print("✅ import成功！")

CWD: /Users/tanaamidaisuke/Documents/python_code/self_learinng/Deeplearning
Before sys.path: ['/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python313.zip', '/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13', '/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload', '', '/Users/tanaamidaisuke/Documents/python_code/self_learinng/Deeplearning/.venv/lib/python3.13/site-packages']
After sys.path: ['/Users/tanaamidaisuke/Documents/python_code/self_learinng/Deeplearning/deep-learning-from-scratch-master', '/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python313.zip', '/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13', '/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload', '', '/Users/tanaamidaisuke/Documents/p

In [3]:
(x_train,t_train),(x_test,t_test)=load_mnist(flatten=True,normalize=False)

In [4]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)
